# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.18

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/student/Documents/DACSC

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/student/Documents/DACSC

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/student/Documents/DACSC/CMakeFiles /home/student/Documents/DACSC//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/student/Documents/DACSC/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ServeurHopital

# Build rule for target.
ServeurHopital: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ServeurHopital
.PHONY : ServeurHopital

# fast build rule for target.
ServeurHopital/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ServeurHopital.dir/build.make CMakeFiles/ServeurHopital.dir/build
.PHONY : ServeurHopital/fast

#=============================================================================
# Target rules for targets named Cli

# Build rule for target.
Cli: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Cli
.PHONY : Cli

# fast build rule for target.
Cli/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Cli.dir/build.make CMakeFiles/Cli.dir/build
.PHONY : Cli/fast

#=============================================================================
# Target rules for targets named TerminalClient

# Build rule for target.
TerminalClient: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 TerminalClient
.PHONY : TerminalClient

# fast build rule for target.
TerminalClient/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TerminalClient.dir/build.make CMakeFiles/TerminalClient.dir/build
.PHONY : TerminalClient/fast

#=============================================================================
# Target rules for targets named Serv

# Build rule for target.
Serv: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Serv
.PHONY : Serv

# fast build rule for target.
Serv/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Serv.dir/build.make CMakeFiles/Serv.dir/build
.PHONY : Serv/fast

ClientConsultationBookerQt/main.o: ClientConsultationBookerQt/main.cpp.o

.PHONY : ClientConsultationBookerQt/main.o

# target to build an object file
ClientConsultationBookerQt/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TerminalClient.dir/build.make CMakeFiles/TerminalClient.dir/ClientConsultationBookerQt/main.cpp.o
.PHONY : ClientConsultationBookerQt/main.cpp.o

ClientConsultationBookerQt/main.i: ClientConsultationBookerQt/main.cpp.i

.PHONY : ClientConsultationBookerQt/main.i

# target to preprocess a source file
ClientConsultationBookerQt/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TerminalClient.dir/build.make CMakeFiles/TerminalClient.dir/ClientConsultationBookerQt/main.cpp.i
.PHONY : ClientConsultationBookerQt/main.cpp.i

ClientConsultationBookerQt/main.s: ClientConsultationBookerQt/main.cpp.s

.PHONY : ClientConsultationBookerQt/main.s

# target to generate assembly for a file
ClientConsultationBookerQt/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TerminalClient.dir/build.make CMakeFiles/TerminalClient.dir/ClientConsultationBookerQt/main.cpp.s
.PHONY : ClientConsultationBookerQt/main.cpp.s

ClientConsultationBookerQt/mainwindowclientconsultationbooker.o: ClientConsultationBookerQt/mainwindowclientconsultationbooker.cpp.o

.PHONY : ClientConsultationBookerQt/mainwindowclientconsultationbooker.o

# target to build an object file
ClientConsultationBookerQt/mainwindowclientconsultationbooker.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TerminalClient.dir/build.make CMakeFiles/TerminalClient.dir/ClientConsultationBookerQt/mainwindowclientconsultationbooker.cpp.o
.PHONY : ClientConsultationBookerQt/mainwindowclientconsultationbooker.cpp.o

ClientConsultationBookerQt/mainwindowclientconsultationbooker.i: ClientConsultationBookerQt/mainwindowclientconsultationbooker.cpp.i

.PHONY : ClientConsultationBookerQt/mainwindowclientconsultationbooker.i

# target to preprocess a source file
ClientConsultationBookerQt/mainwindowclientconsultationbooker.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TerminalClient.dir/build.make CMakeFiles/TerminalClient.dir/ClientConsultationBookerQt/mainwindowclientconsultationbooker.cpp.i
.PHONY : ClientConsultationBookerQt/mainwindowclientconsultationbooker.cpp.i

ClientConsultationBookerQt/mainwindowclientconsultationbooker.s: ClientConsultationBookerQt/mainwindowclientconsultationbooker.cpp.s

.PHONY : ClientConsultationBookerQt/mainwindowclientconsultationbooker.s

# target to generate assembly for a file
ClientConsultationBookerQt/mainwindowclientconsultationbooker.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TerminalClient.dir/build.make CMakeFiles/TerminalClient.dir/ClientConsultationBookerQt/mainwindowclientconsultationbooker.cpp.s
.PHONY : ClientConsultationBookerQt/mainwindowclientconsultationbooker.cpp.s

ClientConsultationBookerQt/moc_mainwindowclientconsultationbooker.o: ClientConsultationBookerQt/moc_mainwindowclientconsultationbooker.cpp.o

.PHONY : ClientConsultationBookerQt/moc_mainwindowclientconsultationbooker.o

# target to build an object file
ClientConsultationBookerQt/moc_mainwindowclientconsultationbooker.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TerminalClient.dir/build.make CMakeFiles/TerminalClient.dir/ClientConsultationBookerQt/moc_mainwindowclientconsultationbooker.cpp.o
.PHONY : ClientConsultationBookerQt/moc_mainwindowclientconsultationbooker.cpp.o

ClientConsultationBookerQt/moc_mainwindowclientconsultationbooker.i: ClientConsultationBookerQt/moc_mainwindowclientconsultationbooker.cpp.i

.PHONY : ClientConsultationBookerQt/moc_mainwindowclientconsultationbooker.i

# target to preprocess a source file
ClientConsultationBookerQt/moc_mainwindowclientconsultationbooker.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TerminalClient.dir/build.make CMakeFiles/TerminalClient.dir/ClientConsultationBookerQt/moc_mainwindowclientconsultationbooker.cpp.i
.PHONY : ClientConsultationBookerQt/moc_mainwindowclientconsultationbooker.cpp.i

ClientConsultationBookerQt/moc_mainwindowclientconsultationbooker.s: ClientConsultationBookerQt/moc_mainwindowclientconsultationbooker.cpp.s

.PHONY : ClientConsultationBookerQt/moc_mainwindowclientconsultationbooker.s

# target to generate assembly for a file
ClientConsultationBookerQt/moc_mainwindowclientconsultationbooker.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TerminalClient.dir/build.make CMakeFiles/TerminalClient.dir/ClientConsultationBookerQt/moc_mainwindowclientconsultationbooker.cpp.s
.PHONY : ClientConsultationBookerQt/moc_mainwindowclientconsultationbooker.cpp.s

MyProtocolsLibrary/CBP.o: MyProtocolsLibrary/CBP.cpp.o

.PHONY : MyProtocolsLibrary/CBP.o

# target to build an object file
MyProtocolsLibrary/CBP.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ServeurHopital.dir/build.make CMakeFiles/ServeurHopital.dir/MyProtocolsLibrary/CBP.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TerminalClient.dir/build.make CMakeFiles/TerminalClient.dir/MyProtocolsLibrary/CBP.cpp.o
.PHONY : MyProtocolsLibrary/CBP.cpp.o

MyProtocolsLibrary/CBP.i: MyProtocolsLibrary/CBP.cpp.i

.PHONY : MyProtocolsLibrary/CBP.i

# target to preprocess a source file
MyProtocolsLibrary/CBP.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ServeurHopital.dir/build.make CMakeFiles/ServeurHopital.dir/MyProtocolsLibrary/CBP.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TerminalClient.dir/build.make CMakeFiles/TerminalClient.dir/MyProtocolsLibrary/CBP.cpp.i
.PHONY : MyProtocolsLibrary/CBP.cpp.i

MyProtocolsLibrary/CBP.s: MyProtocolsLibrary/CBP.cpp.s

.PHONY : MyProtocolsLibrary/CBP.s

# target to generate assembly for a file
MyProtocolsLibrary/CBP.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ServeurHopital.dir/build.make CMakeFiles/ServeurHopital.dir/MyProtocolsLibrary/CBP.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TerminalClient.dir/build.make CMakeFiles/TerminalClient.dir/MyProtocolsLibrary/CBP.cpp.s
.PHONY : MyProtocolsLibrary/CBP.cpp.s

MyQuerriesLibrary/sqlQuerry.o: MyQuerriesLibrary/sqlQuerry.cpp.o

.PHONY : MyQuerriesLibrary/sqlQuerry.o

# target to build an object file
MyQuerriesLibrary/sqlQuerry.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ServeurHopital.dir/build.make CMakeFiles/ServeurHopital.dir/MyQuerriesLibrary/sqlQuerry.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TerminalClient.dir/build.make CMakeFiles/TerminalClient.dir/MyQuerriesLibrary/sqlQuerry.cpp.o
.PHONY : MyQuerriesLibrary/sqlQuerry.cpp.o

MyQuerriesLibrary/sqlQuerry.i: MyQuerriesLibrary/sqlQuerry.cpp.i

.PHONY : MyQuerriesLibrary/sqlQuerry.i

# target to preprocess a source file
MyQuerriesLibrary/sqlQuerry.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ServeurHopital.dir/build.make CMakeFiles/ServeurHopital.dir/MyQuerriesLibrary/sqlQuerry.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TerminalClient.dir/build.make CMakeFiles/TerminalClient.dir/MyQuerriesLibrary/sqlQuerry.cpp.i
.PHONY : MyQuerriesLibrary/sqlQuerry.cpp.i

MyQuerriesLibrary/sqlQuerry.s: MyQuerriesLibrary/sqlQuerry.cpp.s

.PHONY : MyQuerriesLibrary/sqlQuerry.s

# target to generate assembly for a file
MyQuerriesLibrary/sqlQuerry.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ServeurHopital.dir/build.make CMakeFiles/ServeurHopital.dir/MyQuerriesLibrary/sqlQuerry.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TerminalClient.dir/build.make CMakeFiles/TerminalClient.dir/MyQuerriesLibrary/sqlQuerry.cpp.s
.PHONY : MyQuerriesLibrary/sqlQuerry.cpp.s

MySocketLibrary/TCP.o: MySocketLibrary/TCP.cpp.o

.PHONY : MySocketLibrary/TCP.o

# target to build an object file
MySocketLibrary/TCP.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ServeurHopital.dir/build.make CMakeFiles/ServeurHopital.dir/MySocketLibrary/TCP.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Cli.dir/build.make CMakeFiles/Cli.dir/MySocketLibrary/TCP.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TerminalClient.dir/build.make CMakeFiles/TerminalClient.dir/MySocketLibrary/TCP.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Serv.dir/build.make CMakeFiles/Serv.dir/MySocketLibrary/TCP.cpp.o
.PHONY : MySocketLibrary/TCP.cpp.o

MySocketLibrary/TCP.i: MySocketLibrary/TCP.cpp.i

.PHONY : MySocketLibrary/TCP.i

# target to preprocess a source file
MySocketLibrary/TCP.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ServeurHopital.dir/build.make CMakeFiles/ServeurHopital.dir/MySocketLibrary/TCP.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Cli.dir/build.make CMakeFiles/Cli.dir/MySocketLibrary/TCP.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TerminalClient.dir/build.make CMakeFiles/TerminalClient.dir/MySocketLibrary/TCP.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Serv.dir/build.make CMakeFiles/Serv.dir/MySocketLibrary/TCP.cpp.i
.PHONY : MySocketLibrary/TCP.cpp.i

MySocketLibrary/TCP.s: MySocketLibrary/TCP.cpp.s

.PHONY : MySocketLibrary/TCP.s

# target to generate assembly for a file
MySocketLibrary/TCP.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ServeurHopital.dir/build.make CMakeFiles/ServeurHopital.dir/MySocketLibrary/TCP.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Cli.dir/build.make CMakeFiles/Cli.dir/MySocketLibrary/TCP.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TerminalClient.dir/build.make CMakeFiles/TerminalClient.dir/MySocketLibrary/TCP.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Serv.dir/build.make CMakeFiles/Serv.dir/MySocketLibrary/TCP.cpp.s
.PHONY : MySocketLibrary/TCP.cpp.s

ServHopital/ServeurHopital.o: ServHopital/ServeurHopital.cpp.o

.PHONY : ServHopital/ServeurHopital.o

# target to build an object file
ServHopital/ServeurHopital.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ServeurHopital.dir/build.make CMakeFiles/ServeurHopital.dir/ServHopital/ServeurHopital.cpp.o
.PHONY : ServHopital/ServeurHopital.cpp.o

ServHopital/ServeurHopital.i: ServHopital/ServeurHopital.cpp.i

.PHONY : ServHopital/ServeurHopital.i

# target to preprocess a source file
ServHopital/ServeurHopital.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ServeurHopital.dir/build.make CMakeFiles/ServeurHopital.dir/ServHopital/ServeurHopital.cpp.i
.PHONY : ServHopital/ServeurHopital.cpp.i

ServHopital/ServeurHopital.s: ServHopital/ServeurHopital.cpp.s

.PHONY : ServHopital/ServeurHopital.s

# target to generate assembly for a file
ServHopital/ServeurHopital.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ServeurHopital.dir/build.make CMakeFiles/ServeurHopital.dir/ServHopital/ServeurHopital.cpp.s
.PHONY : ServHopital/ServeurHopital.cpp.s

cli.o: cli.cpp.o

.PHONY : cli.o

# target to build an object file
cli.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Cli.dir/build.make CMakeFiles/Cli.dir/cli.cpp.o
.PHONY : cli.cpp.o

cli.i: cli.cpp.i

.PHONY : cli.i

# target to preprocess a source file
cli.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Cli.dir/build.make CMakeFiles/Cli.dir/cli.cpp.i
.PHONY : cli.cpp.i

cli.s: cli.cpp.s

.PHONY : cli.s

# target to generate assembly for a file
cli.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Cli.dir/build.make CMakeFiles/Cli.dir/cli.cpp.s
.PHONY : cli.cpp.s

serv.o: serv.cpp.o

.PHONY : serv.o

# target to build an object file
serv.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Serv.dir/build.make CMakeFiles/Serv.dir/serv.cpp.o
.PHONY : serv.cpp.o

serv.i: serv.cpp.i

.PHONY : serv.i

# target to preprocess a source file
serv.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Serv.dir/build.make CMakeFiles/Serv.dir/serv.cpp.i
.PHONY : serv.cpp.i

serv.s: serv.cpp.s

.PHONY : serv.s

# target to generate assembly for a file
serv.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Serv.dir/build.make CMakeFiles/Serv.dir/serv.cpp.s
.PHONY : serv.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Cli"
	@echo "... Serv"
	@echo "... ServeurHopital"
	@echo "... TerminalClient"
	@echo "... ClientConsultationBookerQt/main.o"
	@echo "... ClientConsultationBookerQt/main.i"
	@echo "... ClientConsultationBookerQt/main.s"
	@echo "... ClientConsultationBookerQt/mainwindowclientconsultationbooker.o"
	@echo "... ClientConsultationBookerQt/mainwindowclientconsultationbooker.i"
	@echo "... ClientConsultationBookerQt/mainwindowclientconsultationbooker.s"
	@echo "... ClientConsultationBookerQt/moc_mainwindowclientconsultationbooker.o"
	@echo "... ClientConsultationBookerQt/moc_mainwindowclientconsultationbooker.i"
	@echo "... ClientConsultationBookerQt/moc_mainwindowclientconsultationbooker.s"
	@echo "... MyProtocolsLibrary/CBP.o"
	@echo "... MyProtocolsLibrary/CBP.i"
	@echo "... MyProtocolsLibrary/CBP.s"
	@echo "... MyQuerriesLibrary/sqlQuerry.o"
	@echo "... MyQuerriesLibrary/sqlQuerry.i"
	@echo "... MyQuerriesLibrary/sqlQuerry.s"
	@echo "... MySocketLibrary/TCP.o"
	@echo "... MySocketLibrary/TCP.i"
	@echo "... MySocketLibrary/TCP.s"
	@echo "... ServHopital/ServeurHopital.o"
	@echo "... ServHopital/ServeurHopital.i"
	@echo "... ServHopital/ServeurHopital.s"
	@echo "... cli.o"
	@echo "... cli.i"
	@echo "... cli.s"
	@echo "... serv.o"
	@echo "... serv.i"
	@echo "... serv.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

